### PR TITLE
Reviewer Alex - Use GETK for mget with a single key

### PR DESCRIPTION
**Pull request by bossmc**
This prevents having to time-out the GETKQ (that we would otherwise do) in the case where the key is absent on the server.  Tested live with the live test framework.

### CODE REVIEW

**Comment by AlexHockey** [comment]
A couple of questions on this.

Firstly, how does this fix actually change anything? `MemcachedStore` only ever calls `memcached_mget` with 1 key. This means we only ever pass `true` into `memcached_mget_by_key_real` (which is the value that has always been passed). Should you be using `!=`?

Secondly, it feels like this fixes single gets but leaves multiple gets broken. Why not pass `false` to `memcached_mget_by_key_real` unconditionally?

**Comment by bossmc** [comment]
Because I failed at refactoring and implemented perfectly the wrong thing.  I initially had `false` passed unconditionally but thought it was better to make the smallest possible functional change (that's where the refactoring error appeared).  We never use multiple-key mgets so I felt happy leaving them as is.

**Comment by AlexHockey** [comment]
As discussed: no fix we make here is likely to be accepted upstream. If we just pass `false` genuine multi-key mgets should just work (though the performance will be worse than if we managed to fixed libmemcached properly). As such passing `false` is preferable, and this also matches what you tested.

**Comment by bossmc** [comment]
Marked up.

**Pull request merged**
