### PR TITLE
[Reviewer: Rob] Fixes for 14.04

### PR DESCRIPTION
**Pull request by eleanor-merry**
Fixes for 14.04

### CODE REVIEW

**Comment by rkd-msw** [comment]
Have you just run autoconf (or something in that family) and checked that in? If so, would it be better to just run autoconf as part of the build process?

**Comment by rkd-msw** [comment]
As discussed, you're running short on time, so I'm going to figure out if we can use autotools better here. (If not, then I have no objections to merging.)

**Comment by rkd-msw** [comment]
It looks like config/compile, config/config.guess, config/config.sub, config/depcomp, config/install-sh, config/ltmain.sh, config/missing, and m4/libtool.m4 will all get rebuilt (from scratch) by autogen.sh, but our make scripts only run that if `configure` doesn't exist, and `make clean` doesn't remove it.

I think we could just remove all these files and get it working by having libmemcached.mk delete `configure` when you run a top-level `make clean`. That feels like the right thing in general - `make clean; make` will rebuild everything from scratch, rather than reusing the `configure` file created on the original build. Sound OK?

(I'm happy to do the tedious update-every-instance-of-`libmemcached.mk` work - this comment is just to check that you and @bossmc agree that this is the right approach.)

**Comment by eleanor-merry** [comment]
I'm happy with that

**Pull request merged**
